# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend-config
#   namespace: expense-k8
# data:
#   DB_HOST: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense-k8
  labels:
    component: frontend
    project: expense
    tier: web
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: web
      env: dev
  template:
    metadata:
      labels:
        component: frontend
        project: expense
        tier: web
        env: dev
    spec:
      containers:
        - name: frontend
          image: joindevops/frontend:1.0
          # envFrom:
          # - configMapRef:
          #     name: frontend-config

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense-k8
spec:
  type: LoadBalancer
  selector:
      component: frontend
      project: expense
      tier: web
      env: dev  
  ports:
    - protocol: TCP 
      port: 80  #service port
      targetPort: 80 # target port 