apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense-k8
  labels:
    component: mysql
    project: expense
    tier: database
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: database
      env: dev
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: database
        env: dev
    spec:
      containers:
        - name: mysql
          image: joindevops/mysql:v1.0

...
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense-k8
spec:
  selector:
      component: mysql
      project: expense
      tier: database
      env: dev  
  ports:
    - protocol: TCP 
      port: 3306  #service port
      targetPort: 3306 # target port 
  type: ClusterIP